runtime: python39

entrypoint: gunicorn --bind :$PORT app:app

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  FLASK_APP: "app"
  FLASK_ENV: "production"
  SQLALCHEMY_DATABASE_URI: "sqlite:////tmp/mydatabase.db"  # Updated path

includes:
- requirements.txt